#!/usr/bin/env bash
# Installs nginx and configures /redirect_me to redirect with 301 status

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html

sed -i '/server_name _;/a \    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-enabled/default

service nginx start
