#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to YouTube

apt-get update -y
apt-get install -y nginx

mkdir -p /var/www/html

# Add redirection to default site
sed -i '/server_name localhost;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-enabled/default

service nginx restart

