#!/usr/bin/env bash
# Configures a new Ubuntu machine to serve a custom 404 page with Nginx

# Install nginx if not installed
apt-get update -y
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html > /dev/null

# Replace default site config with required setup
cat > /etc/nginx/sites-enabled/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart Nginx
service nginx restart

