#!/usr/bin/env bash
# Installs nginx and configures custom 404 error page

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a \    error_page 404 /404.html;\n    location = /404.html { internal; }\n    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-enabled/default

service nginx start
